[package]
name = "arroyo-node"

authors.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
readme.workspace = true
edition.workspace = true

[dependencies]
arroyo-types = { path = "../arroyo-types" }
arroyo-rpc = { path = "../arroyo-rpc" }
arroyo-server-common = { path = "../arroyo-server-common" }

tonic = { workspace = true }
tonic-reflection = { workspace = true }
prost = "0.12"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
fork = "0.1"
rand = "0.8"
local-ip-address = "0.5"
lazy_static = "1.4.0"
prometheus = "0.13.3"
tokio-stream = "0.1.14"
anyhow = "1.0.72"
base64 = "0.22.0"