[package]
name = "arroyo-node"
version = "0.16.0-dev"
edition = "2024"

[dependencies]
arroyo-types = { path = "../arroyo-types" }
arroyo-rpc = { path = "../arroyo-rpc" }
arroyo-server-common = { path = "../arroyo-server-common" }

tonic = { workspace = true }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
rand = { workspace = true }
lazy_static = "1.4.0"
prometheus = { workspace = true }
anyhow = "1.0.72"
uuid = { version =  "1.17.0", features = ["v4"] }