[package]
name = "arroyo-server-common"
version = "0.16.0-dev"
edition = "2021"

[dependencies]
arroyo-types = { path = "../arroyo-types" }
arroyo-rpc = { path = "../arroyo-rpc" }

jemalloc_pprof = "0.7.0"

# logging
json-subscriber = "0.2.6"
tracing = "0.1"
tracing-logfmt = "0.2.0"
tracing-subscriber = {version = "0.3", features = [ "env-filter", "json" ]}
tracing-appender = "0.2"
tracing-log = "0.2"

# middleware
tower = { workspace = true }
tower-http = {workspace = true, features = ["trace", "fs", "validate-request", "auth"]}
tonic = { workspace = true }
tokio = { version = "1", features = ["full"] }
prometheus = {workspace = true, features = ["process"] }
axum = {workspace = true}
axum-server = { version = "0.7", features = ["tls-rustls"] }
http = "1"

lazy_static = "1.4.0"
futures = { version = "0.3" }
once_cell = "1.17.1"
reqwest = { workspace = true, features = ["json"] }
serde_json = "1.0.96"
tokio-util = "0.7.10"
anyhow = "1.0.82"
toml = "0.8.13"
dirs = "6"
uuid = { version = "1.8.0", features = ["v4"] }
url = { version = "2.5" }
rustls = { workspace = true, features = ["std", "aws_lc_rs"] }
rustls-pemfile = { workspace = true }
webpki-roots = { workspace = true }

# profile
flate2 = "1.0.30"
pprof = { version = "0.15.0", features = ["flamegraph", "protobuf-codec"] }
serde = { version = "1.0.96", features = ["derive"] }

[build-dependencies]
vergen = { version = "8.0.0", features = ["build", "cargo", "git", "gitcl"] }

