[package]
name = "arroyo-udf-common"
version = "0.2.1"
edition = "2024"
authors = ["Arroyo Systems <support@arroyo.systems>"]
license = "MIT OR Apache-2.0"
readme = "../../../README.md"
repository = "https://github.com/ArroyoSystems/arroyo"
homepage = "https://arroyo.dev"
categories = ["database-implementations", "web-programming"]
keywords = ["streaming", "data", "sql", "event-processing"]

description = "Common utilities for the Arroyo UDF FFI API"

[dependencies]
arrow = { workspace = true, features = ["ffi"]}
syn = { version = "2", features = ["full"] }
anyhow = "1.0.82"
regex = "1.10.3"
serde = { version = "1.0.197", features = ["derive"] }
