[package]
name = "arroyo-rpc"
version = "0.13.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arroyo-types = { path = "../arroyo-types" }

arrow = { workspace = true }
arrow-array = { workspace = true }
arrow-ord = { workspace = true }
arrow-schema = {workspace = true, features = ["serde"]}
tonic = { workspace = true }
prost = {workspace = true}
prost-reflect = "0.13.1"
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3.30" }
bincode = "2.0.0-rc.3"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
nanoid = "0.4"
utoipa = "4"
anyhow = "1"
reqwest = { version = "0.11.22", features = ["default", "serde_json", "json"] }
log = "0.4.20"
tracing = "0.1.40"
async-trait = "0.1.74"
apache-avro = "0.16.0"
regex = "1.9.5"
base64 = "0.21.5"
ahash = "0.8.7"
strum_macros = "0.26.2"
strum = "0.26.2"
figment = { version = "0.10", features = ["toml", "env", "yaml", "json"] }
k8s-openapi = { version = "0.22.0", features = ["v1_30"] }
url = { version = "2", features = ["serde"] }
dirs = "5.0.1"
arc-swap = "1.7.1"
datafusion-common = { workspace = true }
rand = "0.8.5"

[build-dependencies]
tonic-build = { workspace = true }

[dev-dependencies]
figment = {version = "0.10", features = ["test"]}
