[package]
name = "arroyo-metrics"
version = "0.15.0"
edition = "2021"

[dependencies]
arroyo-types = { path = "../arroyo-types" }
prometheus = { workspace = true, features = ["process"] }
lazy_static = "1.4.0"
