[package]
name = "arroyo-metrics"
version = "0.11.2"
edition = "2021"

[dependencies]
arroyo-types = { path = "../arroyo-types" }
prometheus = {version = "0.13", features = ["process"] }
lazy_static = "1.4.0"
