[package]
name = "arroyo-metrics"
version = "0.16.0-dev"
edition = "2024"

[dependencies]
arroyo-types = { path = "../arroyo-types" }
prometheus = { workspace = true, features = ["process"] }
lazy_static = "1.4.0"
