[package]
name = "arroyo-openapi"
version = "0.10.1"
edition = "2021"

[dependencies]
arroyo-api = { path = "../arroyo-api" }
serde = "^1.0"
serde_derive = "^1.0"
serde_with = "3.0.0"
serde_json = "^1.0"
url = "^2.2"
reqwest = "0.11.18"

[build-dependencies]
arroyo-api = { path = "../arroyo-api" }
utoipa = "4"
