[package]
name = "arroyo-openapi"
version = "0.15.0-dev"
edition = "2021"

[dependencies]
futures = "0.3"
progenitor-client = { git = "https://github.com/oxidecomputer/progenitor" }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

chrono = { version = "0.4", features = ["serde"] }
regress = "0.10.1"

[build-dependencies]
prettyplease = "0.1.25"
progenitor = { version = '0.8' }
serde_json = "1.0"
syn = "1.0"

utoipa = {workspace = true}
arroyo-api = { path = "../arroyo-api" }