[package]
name = "arroyo-openapi"
version = "0.15.0"
edition = "2021"

[dependencies]
progenitor-client = { git = "https://github.com/oxidecomputer/progenitor" }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
prettyplease = "0.2"
progenitor = { version = '0.11' }
serde_json = "1.0"
syn = "2"

utoipa = {workspace = true}
arroyo-api = { path = "../arroyo-api" }