[package]
name = "arroyo-state"
version = "0.16.0-dev"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arroyo-types = { path = "../arroyo-types" }
arroyo-rpc = { path = "../arroyo-rpc" }
arroyo-storage = { path = "../arroyo-storage" }
arroyo-datastream = { path = "../arroyo-datastream" }

datafusion = { workspace = true }

anyhow = "1.0"
tracing = "0.1"
bincode = {workspace = true}
tokio = { version = "1", features = ["full", "tracing"] }
arrow = { workspace = true }
arrow-ord = { workspace = true }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
parquet = { workspace = true }
async-trait = "0.1.68"
once_cell = "1.17.1"
futures = "0.3"
prost = {workspace = true}
prometheus = { workspace = true }
lazy_static = "1.4.0"
object_store = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1"