[package]
name = "arroyo-types"
version = "0.16.0-dev"
edition = "2024"

[dependencies]
bincode = { workspace = true }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
arrow = { workspace = true }
arrow-array = { workspace = true }
