[package]
name = "arroyo-types"
version = "0.11.3"
edition = "2021"

[dependencies]
bincode = "2.0.0-rc.3"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
arrow = { workspace = true }
arrow-array = { workspace = true }
